version: "3.9"
services:
  pagina:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - cache
    networks:
      - rede-interna

  cache:
    image: "redis:alpine"
    networks:
      - rede-interna

  administrador:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - rede-interna

networks:
  rede-interna: